trivy:
  dbRepository: ghcr.io/aquasecurity/trivy-db
  image:
    tag: "0.53.0"
  vulnType: "os,library"

vulnerabilityReports:
  scannerName: Trivy

scanJob:
  image:
    tag: "0.53.0"
  scanners:
    - Vulnerability

serviceMonitor:
  enabled: false

trivy-operator:
  scanJob:
    scanOnlyCurrentRevisions: true

namespaceSelector:
  matchLabels: {}
  # Scan all namespaces by default

podSecurityStandards:
  enabled: false
