apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "earthquake-app-chart.fullname" . }}-config
  labels:
    {{- include "earthquake-app-chart.labels" . | nindent 4 }}
data:
  DATABASE_HOST: "{{ include "earthquake-app-chart.fullname" . }}-postgres"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "{{ .Values.postgresql.database }}"
  DATABASE_USER: "{{ .Values.postgresql.username }}"
