apiVersion: v1
kind: Service
metadata:
  name: {{ include "earthquake-app-chart.fullname" . }}-frontend
  labels:
    {{- include "earthquake-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "earthquake-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
