apiVersion: v1
kind: Secret
metadata:
  name: {{ include "earthquake-app-chart.fullname" . }}-postgres-secret
  labels:
    {{- include "earthquake-app-chart.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
