apiVersion: v1
kind: Service
metadata:
  name: {{ include "earthquake-app-chart.fullname" . }}-postgres
  labels:
    {{- include "earthquake-app-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    {{- include "earthquake-app-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
